### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dkhabarov** [reverbrain/rift#6]
``` shell
(gdb) run /usr/bin/rift_server -c /etc/rift.json 
Starting program: /usr/bin/rift_server /usr/bin/rift_server -c /etc/rift.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Failed to initialize logger: "logger.frontends" field is missed
Failed to initialize logger

Program received signal SIGSEGV, Segmentation fault.
ioremap::rift::async_performer::stop (this=0x0) at /tmp/buildd/rift-2.26.0.1.0/src/async_performer.cpp:21
21      /tmp/buildd/rift-2.26.0.1.0/src/async_performer.cpp: No such file or directory.
(gdb) backtrace fu
#0  ioremap::rift::async_performer::stop (this=0x0) at /tmp/buildd/rift-2.26.0.1.0/src/async_performer.cpp:21
No locals.
#1  0x000000000047f238 in rift_server::example_server::~example_server (this=0x724db8, __in_chrg=<optimized out>) at /tmp/buildd/rift-2.26.0.1.0/src/rift_server.cpp:10
No locals.
#2  0x0000000000492889 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x724da0) at /usr/include/c++/4.8/bits/shared_ptr_base.h:144
No locals.
#3  0x00000000004929cb in ~__shared_count (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr_base.h:546
No locals.
#4  ~__shared_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr_base.h:781
No locals.
#5  ~shared_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/shared_ptr.h:93
No locals.
#6  ioremap::thevoid::run_server<rift_server::example_server> (argc=<optimized out>, argv=0x7fffffffe658) at /usr/include/thevoid/server.hpp:395
No locals.
#7  0x00007ffff5c05ec5 in __libc_start_main (main=0x47d810 <main(int, char**)>, argc=4, argv=0x7fffffffe658, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe648) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 3915220639307476290, 4709141, 140737488348752, 0, 0, -3915220638445130430, -3915242237574173374}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x4e4c30 <__libc_csu_init>, 0x7fffffffe658}, data = {prev = 0x0, cleanup = 0x0, canceltype = 5131312}}}
        not_first_call = <optimized out>
#8  0x000000000047db3e in _start ()
```

OS: Ubuntu 14.4. 

``` shell
# uname -a
Linux elliptics1 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Installed from repo:
deb http://repo.reverbrain.com/trusty/ current/amd64/

**Comment by dkhabarov** [comment]
Segfault fixes after fixed error in config file: Failed to initialize logger: "logger.frontends" field is missed

**Comment by bioothod** [comment]
Yes, rift doesn't catch logger initialization errors.

Also, it is not supported, you can use backrunner proxy instead: http://doc.reverbrain.com/backrunner:backrunner
If you submit a patch to fix this issue, it will be merged of course.

**Comment by dkhabarov** [comment]
Unfortunately, I'm not so good to know C++, to write the patch.

**Comment by bioothod** [comment]
Okay, I recommend trying backrunner proxy, it is very similar to rift and most of the URI handlers are the same

**Comment by dkhabarov** [comment]
Ok. Thx.
